qiniu/reviewbot

internal/linters/go/staticcheck/staticcheck.go
internal/linters/go/staticcheck/staticcheck_test.go

feat(staticcheck): turn off compile errors by default

---

deploy/reviewbot.yaml
github.go
main.go
server.go

fix: support work on other org

---

internal/linters/git-flow/commit-check/commit_check.go
internal/linters/git-flow/commit-check/commit_check_test.go
main.go

feat(commit-check): add amend suggestion

---

config/config.go
internal/linters/util.go
server.go

doc: use english

---

docs/engineering-practice/git-flow-instructions_zh.md

Add git references:
- Git Conventional Commits
- Git Flight Rules

Add more git references documents

---

internal/linters/go/gofmt/gofmt.go

_**issue：**_
**_There should be a blank line between lines 41 and 42, but the suggestion did not display correctly._**
_**The result after the fix：**_

fix(gofmt): Resolve the issue of missing blank lines  not being displayed in comments

---

internal/linters/github.go
internal/linters/go/staticcheck/staticcheck.go
internal/linters/go/staticcheck/staticcheck_test.go
internal/linters/linters.go

fix(staticcheck): ignore go-zero custom json tag

---

internal/linters/doc/note-check/doc.go
internal/linters/doc/note-check/note.go
internal/linters/doc/note-check/note_test.go
internal/linters/doc/note-check/testdata/note.go
internal/linters/filters.go
internal/linters/linters.go
main.go

feat: add note checker

---

Dockerfile
docs/website/docs/components/shell/_category_.json
docs/website/docs/components/shell/shellcheck.md
internal/linters/shell/shellcheck/shellcheck.go
main.go

feat: add shellcheck linter

---

config/config.go
config/config_test.go
server.go

refactor(config): refactor config

---

Dockerfile
config/config.yaml

golangci-lint: enable all linters for specific repo for gray testing

---

Dockerfile
Makefile

build: reduce docker image size

---

Dockerfile
Makefile

build: remove unnecessary tools and add specific tag

---

main.go

https://github.com/qiniu/reviewbot/issues/132

feat: add Profiling support

---

config/linters-config/.golangci.yml
internal/linters/linters.go

feat: disable warpcheck and gochecknoglobals linter

---

internal/linters/filters.go
internal/linters/hunk.go
internal/linters/hunk_test.go

fix https://github.com/qiniu/reviewbot/issues/179

fix(hunk): starLine was not being validated by the InHunk function

---

internal/linters/doc/note-check/note.go

fix(note-check): skip deleted file

---

config/config.yaml
config/config_test.go
config/linters-config/.golangci.goplus.yml
deploy/reviewbot.yaml

related https://github.com/goplus/llgoexamples/pull/4

deploy: use custom golangci-lint config for goplus org

---

.github/workflows/image.yaml

close  https://github.com/qiniu/reviewbot/issues/157
copy from 
- https://github.com/jimyag/TheOnlyMirror/blob/self/.github/workflows/image.yaml 
- https://github.com/jimyag/TheOnlyMirror/pkgs/container/one-mirror

build: release container image with github action

---

config/config.yaml

depoly: set GO111MODULE before executing go mod tidy

---

internal/linters/github.go
internal/runner/runner.go

fix: limit the number of annotations

---

internal/linters/linters.go
internal/runner/docker.go
internal/runner/runner.go
main.go

feat(viewer): add html page for log view

---

internal/linters/go/gomodcheck/gomodcheck.go
internal/linters/go/gomodcheck/gomodcheck_test.go

fix https://github.com/qiniu/reviewbot/issues/376

fix(gomodcheck): ignore non-local repalce

---

config/config.go
internal/runner/kubernertes.go
main.go
server.go

refactor: enhance kubernetes runner

---

config/linters-config/linter-reference.json
internal/linters/filters.go
internal/linters/linters.go
main.go
server.go

resolve  https://github.com/qiniu/reviewbot/issues/385
effect：

ehance: provide knowledge information or reference about linter comments

---

config/config.yaml
internal/linters/agent.go
internal/linters/linters.go
internal/linters/provider.go
internal/linters/providergithub.go
main.go

ehance: github pr review comment dispaly more information about linter reference

---

config/config.go
internal/cache/issuereference.go
internal/linters/agent.go
internal/linters/providergithub.go

feat: new github mix report type

---

config/linters-config/.golangci.goplus.yml
config/linters-config/.golangci.yml

deploy: disable canonicalheader
